# coding: utf-8

"""
    AnonTech_Vizivault API

    A service for securely and safely managing user data  # noqa: E501

    OpenAPI spec version: 1.05
    Contact: devin.croak@anontechnology.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "vizivault"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]


setup(
    name=NAME,
    version=VERSION,
    description="Anontech Vizivault API",
    author_email="devin.croak@anontechnology.com",
    url="",
    keywords=["Swagger", "Nox API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    A service for securely and safely managing user data  # noqa: E501
    """
)
